// Egyptian Creativity - Unified Product Data
// This file contains all products used across the site for cart, wishlist, gallery, shop, etc.

const allProducts = [
  {
    id: 1,
    title: "Ancient Pharaoh Mask",
    name: "Ancient Pharaoh Mask",
    category: "jewelry",
    price: 12500,
    originalPrice: 15000,
    image: "images/1-7-scaled.jpg",
    description: "An exquisite reproduction of the legendary burial mask, crafted with 24-karat gold and precious gemstones in the traditional Egyptian style.",
    rating: 4.8,
    reviews: 24,
    badges: ["featured"],
    inStock: true,
    quantity: 15,
    maxQuantity: 15,
    sku: "EGY-001",
    features: ["24K Gold Plated", "Handcrafted", "Museum Quality"],
    badge: "premium",
    availability: "in-stock"
  },
  {
    id: 2,
    title: "Sacred Ankh Pendant",
    name: "Sacred Ankh Pendant",
    category: "jewelry",
    price: 3750,
    originalPrice: null,
    image: "images/4-5-scaled.jpg",
    description: "Symbol of eternal life, this magnificent ankh is crafted from pure gold with intricate engravings representing the cycle of life and death.",
    rating: 4.9,
    reviews: 18,
    badges: ["new"],
    inStock: true,
    quantity: 8,
    maxQuantity: 8,
    sku: "ANK-002",
    features: ["Pure Gold", "Hand Engraved", "Adjustable Chain"],
    badge: "new",
    availability: "in-stock"
  },
  {
    id: 3,
    title: "Royal Canopic Jars",
    name: "Royal Canopic Jars",
    category: "boxes",
    price: 8900,
    originalPrice: 10500,
    image: "images/5-1 (1).jpg",
    description: "Four magnificent vessels representing the sons of Horus, each meticulously detailed with hieroglyphic inscriptions and gold leaf accents.",
    rating: 4.7,
    reviews: 32,
    badges: ["sale"],
    inStock: true,
    quantity: 5,
    maxQuantity: 5,
    sku: "CPJ-003",
    features: ["Hand Painted", "Ceramic", "Set of 4"],
    badge: "sale",
    availability: "in-stock"
  },
  {
    id: 4,
    title: "Divine Scarab Amulet",
    name: "Divine Scarab Amulet",
    category: "jewelry",
    price: 2850,
    originalPrice: null,
    image: "images/5-1.jpg",
    description: "A stunning set of protective amulets featuring intricate scarab designs, symbolizing rebirth and eternal life in ancient Egyptian culture.",
    rating: 4.6,
    reviews: 15,
    badges: [],
    inStock: true,
    quantity: 12,
    maxQuantity: 12,
    sku: "SCB-004",
    features: ["Protective", "Handcrafted"],
    badge: null,
    availability: "in-stock"
  },
  {
    id: 5,
    title: "Cleopatra's Crown Replica",
    name: "Cleopatra's Crown Replica",
    category: "accessories",
    price: 18750,
    originalPrice: null,
    image: "images/5-3.jpg",
    description: "A breathtaking reproduction of the legendary queen's crown, adorned with precious stones and intricate goldwork fit for royalty.",
    rating: 4.9,
    reviews: 28,
    badges: ["featured"],
    inStock: true,
    quantity: 3,
    maxQuantity: 3,
    sku: "CLR-005",
    features: ["Precious Stones", "Goldwork"],
    badge: "featured",
    availability: "in-stock",
    buyWithBox: true,
    boxPrice: 2500
  },
  {
    id: 6,
    title: "Hieroglyphic Papyrus Scroll",
    name: "Hieroglyphic Papyrus Scroll",
    category: "decorations",
    price: 1250,
    originalPrice: 1500,
    image: "images/9-1.jpg",
    description: "Authentic papyrus scroll featuring ancient Egyptian scenes and hieroglyphic texts, handcrafted by skilled artisans.",
    rating: 4.5,
    reviews: 41,
    badges: ["sale"],
    inStock: true,
    quantity: 20,
    maxQuantity: 20,
    sku: "HPS-006",
    features: ["Handcrafted", "Authentic Papyrus"],
    badge: "sale",
    availability: "in-stock"
  },
  {
    id: 7,
    title: "Pharaoh's Scepter Replica",
    name: "Pharaoh's Scepter Replica",
    category: "accessories",
    price: 6500,
    originalPrice: null,
    image: "images/10.jpg",
    description: "Magnificent replica of a pharaoh's ceremonial scepter with golden finish and precious stone inlays.",
    rating: 4.8,
    reviews: 12,
    badges: ["new"],
    inStock: true,
    quantity: 2,
    maxQuantity: 2,
    sku: "PSR-007",
    features: ["Golden Finish", "Precious Stones"],
    badge: "new",
    availability: "in-stock",
    buyWithBox: true,
    boxPrice: 1800
  },
  {
    id: 8,
    title: "Isis Goddess Statue",
    name: "Isis Goddess Statue",
    category: "decorations",
    price: 4200,
    originalPrice: null,
    image: "images/9-1.jpg",
    description: "Beautiful statue of the goddess Isis, protector of magic and motherhood, crafted in bronze with gold accents.",
    rating: 4.7,
    reviews: 19,
    badges: [],
    inStock: true,
    quantity: 7,
    maxQuantity: 7,
    sku: "IGS-008",
    features: ["Bronze", "Gold Accents"],
    badge: null,
    availability: "in-stock"
  },
  {
    id: 9,
    title: "Senet Game Board",
    name: "Senet Game Board",
    category: "accessories",
    price: 3200,
    originalPrice: 3800,
    image: "images/logo.jpg",
    description: "Ancient Egyptian board game of Senet, the game of passing, complete with playing pieces and instructions.",
    rating: 4.9,
    reviews: 35,
    badges: ["sale", "featured"],
    inStock: true,
    quantity: 4,
    maxQuantity: 4,
    sku: "SGB-009",
    features: ["Board Game", "Complete Set"],
    badge: "featured",
    availability: "in-stock",
    buyWithBox: true,
    boxPrice: 1200
  },
  {
    id: 10,
    title: "Nefertiti Bust Replica",
    name: "Nefertiti Bust Replica",
    category: "decorations",
    price: 2800,
    originalPrice: null,
    image: "images/1-7-scaled.jpg",
    description: "Stunning replica of the famous Nefertiti bust, capturing the beauty and elegance of the ancient queen.",
    rating: 4.6,
    reviews: 52,
    badges: [],
    inStock: true,
    quantity: 25,
    maxQuantity: 25,
    sku: "NBR-010",
    features: ["Detailed Painting", "Elegant"],
    badge: null,
    availability: "in-stock"
  },
  // ... Add all other products from PRODUCTS_DATA and galleryData here ...
];

// Export for use in all scripts
if (typeof window !== 'undefined') {
  window.allProducts = allProducts;
} 