USE `egyptian_creativity-v2`;

-- Sample Data for Products (matching existing structure)
INSERT INTO products (product_sku, name, description, price, stock, category, type, has_box, rating, review_count) VALUES
('PHAR-001', 'Pharaoh Necklace', 'Exquisite gold-plated necklace featuring ancient Egyptian hieroglyphics and pharaoh motifs. Perfect for special occasions and cultural celebrations.', 299.99, 15, 1, 'featured', 1, 4.8, 12),
('ANKH-002', 'Ankh Cross Pendant', 'Sacred Ankh symbol pendant in sterling silver with detailed engravings. Represents eternal life and protection.', 89.99, 25, 1, 'new', 0, 4.6, 8),
('HORUS-003', 'Eye of Horus Bracelet', 'Beautiful bracelet featuring the protective Eye of Horus symbol. Handcrafted with attention to detail.', 149.99, 20, 1, 'featured', 1, 4.9, 15),
('SCARAB-004', 'Egyptian Scarab Ring', 'Ancient scarab beetle ring symbolizing rebirth and transformation. Available in various sizes.', 199.99, 12, 1, 'sale', 0, 4.7, 10),
('PYRAMID-005', 'Pyramid Wall Art', 'Stunning pyramid wall decoration with golden accents. Perfect for home or office decor.', 399.99, 8, 2, 'featured', 1, 4.5, 6);

-- Sample Data for Gallery Items (matching existing structure)
INSERT INTO gallery_items (title, category, price, image, description, details) VALUES
('Ancient Egyptian Jewelry Collection', 'Jewelry', 299.99, 'images/gallery/jewelry-collection.jpg', 'A stunning collection of handcrafted jewelry pieces inspired by ancient Egyptian designs and symbols.', 'Handcrafted with premium materials including gold-plated brass and genuine stones. Each piece is individually crafted by skilled artisans.'),
('Pharaoh\'s Throne Replica', 'Decorations', 599.99, 'images/gallery/pharaoh-throne.jpg', 'Detailed replica of an ancient Egyptian throne with intricate carvings and golden finish.', 'Made from solid wood with hand-carved hieroglyphics and gold leaf accents. Perfect for home decor or cultural displays.'),
('Sacred Ankh Symbols', 'Accessories', 89.99, 'images/gallery/ankh-symbols.jpg', 'Collection of sacred Ankh symbols in various sizes and materials, representing eternal life.', 'Available in sterling silver, gold-plated brass, and bronze. Each symbol is carefully crafted to maintain authentic proportions.'),
('Egyptian Temple Architecture', 'Decorations', 799.99, 'images/gallery/temple-architecture.jpg', 'Miniature replicas of famous Egyptian temples with authentic architectural details.', 'Detailed miniature replicas of famous temples including Karnak, Luxor, and Abu Simbel. Made from high-quality resin with hand-painted details.'),
('Nile River Artwork', 'Decorations', 199.99, 'images/gallery/nile-river-art.jpg', 'Beautiful artwork depicting the Nile River with ancient Egyptian boats and landscapes.', 'Hand-painted canvas artwork featuring the Nile River with traditional Egyptian boats and palm trees. Available in various sizes.');

-- Sample Data for Blogs (matching existing structure)
INSERT INTO blogs (title, content, excerpt, author, status, image) VALUES
('The History of Egyptian Jewelry', 'Egyptian jewelry has a rich history dating back thousands of years. The ancient Egyptians were master craftsmen who created stunning pieces using gold, silver, and precious stones. These pieces were not just decorative but held deep religious and cultural significance. The Ankh symbol, representing eternal life, was commonly used in jewelry designs. Pharaohs and nobility wore elaborate pieces to display their status and power. Today, modern artisans continue to create beautiful Egyptian-inspired jewelry that honors these ancient traditions while appealing to contemporary tastes. Our collection features handcrafted pieces that capture the essence of ancient Egyptian design while using modern techniques and materials.', 'Discover the fascinating history behind ancient Egyptian jewelry and how it continues to inspire modern designs.', 'Dr. Sarah Ahmed', 'published', 'images/blogs/egyptian-jewelry-history.jpg'),
('Symbols of Ancient Egypt', 'Ancient Egyptian symbols hold deep meaning and were used extensively in art, architecture, and daily life. The Eye of Horus, for example, represents protection, royal power, and good health. The Ankh symbol, shaped like a cross with a loop at the top, symbolizes eternal life and was often carried by gods and pharaohs. The Scarab beetle represents rebirth and transformation, as the ancient Egyptians observed how these beetles rolled balls of dung, which they associated with the sun god Ra rolling the sun across the sky. The Lotus flower symbolizes rebirth and purity, as it closes at night and reopens in the morning. These symbols continue to inspire artists and designers today, appearing in modern jewelry, home decor, and artwork.', 'Explore the powerful symbols that defined ancient Egyptian culture and their lasting influence on modern design.', 'Prof. Michael Hassan', 'published', 'images/blogs/egyptian-symbols.jpg'),
('Crafting Egyptian-Inspired Home Decor', 'Creating Egyptian-inspired home decor involves understanding the principles of ancient Egyptian design while adapting them for modern living spaces. Key elements include the use of gold and rich colors, geometric patterns, and symbolic motifs. When designing Egyptian-themed rooms, consider incorporating elements like pyramid shapes, lotus flower patterns, and hieroglyphic-inspired artwork. Color palettes should feature deep blues, rich golds, and warm earth tones. Materials like wood, stone, and metal work well to create authentic-looking pieces. Our collection includes handcrafted items that bring the elegance of ancient Egypt into contemporary homes, from wall art to decorative accessories.', 'Learn how to incorporate the timeless elegance of ancient Egyptian design into your modern home decor.', 'Interior Designer Fatima Ali', 'published', 'images/blogs/egyptian-home-decor.jpg');

-- Sample Data for Orders (matching existing structure)
INSERT INTO orders (user_id, shipping_address_id, transaction_id, total_price, status, notes, customer_notes) VALUES
(1, 1, 'TXN-001-2025', 389.98, 'completed', 'Gift for anniversary', 'Please wrap as gift'),
(2, 2, 'TXN-002-2025', 149.99, 'processing', 'Birthday gift', 'Express shipping preferred'),
(3, 3, 'TXN-003-2025', 799.98, 'pending', 'Collection pieces', 'Handle with care'),
(4, 4, 'TXN-004-2025', 399.99, 'completed', 'Home decoration', 'Standard shipping'),
(5, 5, 'TXN-005-2025', 309.98, 'processing', 'Gift set', 'Include gift card'); 